src/WebSales.WebInterface/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using WebSales.Domain.Entities;
using WebSales.Services.DTOs;
using WebSales.Services.Interfaces;

namespace WebSales.WebInterface.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly IProductService _productService;
        private readonly IValueObjectService _valueObjectService;

        public CustomersController(ICustomerService customerService, IValueObjectService valueObjectService, IProductService productService)
        {
            _customerService = customerService;
            _valueObjectService = valueObjectService;
            _productService = productService;
        }

        public async Task<ActionResult> Index()
        {
            var customerDto = await _customerService.GetCustomersAsync();
            return View(customerDto);
        }

        public async Task<ActionResult> Details(int id)
        {
            var customerDto = await _customerService.FindCustomerByIdAsync(id);
            var productsDto = await _productService.ProductsPurchasedByCustomerAsync(id);
            customerDto.ProductsPurchased = productsDto;
            if (customerDto == null) return RedirectToAction(nameof(Index));
            return View(customerDto);
        }

        public ActionResult Create()
        {
            var customerDto = new CustomerDTO();
            return View(customerDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CustomerDTO customerDto)
        {
            var documentExists = await _customerService.CheckIfDocumentExists(customerDto.Document);
            
            if (documentExists)
            {
                ModelState.AddModelError("Document", "This document already exists");
                return View(customerDto);
            }

            if (!ModelState.IsValid) return View(customerDto);

            await _customerService.AddCustomerAsync(customerDto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Edit(int id)
        {
            var customerDto = await _customerService.FindCustomerByIdAsync(id);
            if (customerDto != null)
                return View(customerDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CustomerDTO customerDto)
        {
            var oldCustomer = await _customerService.FindCustomerByIdAsync(customerDto.Id.Value);
            if (customerDto.Id != oldCustomer.Id && oldCustomer.Id != 0)
            {
                ModelState.AddModelError("Document", "This document already exists");
                return View(customerDto);
            }


            customerDto.IsLegalPerson = oldCustomer.IsLegalPerson;
            await _customerService.UpdateCustomerAsync(customerDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task Delete(int id)
        {
            await _customerService.RemoveCustomerByIdAsync(id);
        }
    }
}

src/WebSales.WebInterface/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using WebSales.Services.DTOs;
using WebSales.Services.Interfaces;

namespace WebSales.WebInterface.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<ActionResult> Index()
        {
            var product = await _productService.GetProductsAsync();
            return View(product);
        }

        public async Task<ActionResult> Details(int id)
        {
            var product = await _productService.FindProductByIdAsync(id);

            if (product == null) 
                return RedirectToAction(nameof(Index));

            return View(product);
        }

        public ActionResult Create()
        {
            var product = new ProductDTO();
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductDTO productDto)
        {
            if (!ModelState.IsValid) return View(productDto);
            await _productService.AddProductAsync(productDto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Edit(int id)
        {
            var product = await _productService.FindProductByIdAsync(id);
            if (product == null) return RedirectToAction(nameof(Index));
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductDTO productDto)
        {
            if (!ModelState.IsValid) return View(productDto);
            await _productService.UpdateProductAsync(productDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task Delete(int id)
        {
            await _productService.DeleteProductAsync(id);
        }

        [HttpGet]
        public async Task<ActionResult> FindProductById(int id)
        {
            return Ok(await _productService.FindProductByIdAsync(id));
        }
    }
}

src/WebSales.WebInterface/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using WebSales.Services.DTOs;
using WebSales.Services.Interfaces;

namespace WebSales.WebInterface.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISaleService _saleService;
        private readonly IProductService _productService;
        private readonly IValueObjectService _valueObjectsService;

        public SalesController(ISaleService saleService, IValueObjectService productSoldService, IProductService productService)
        {
            _saleService = saleService;
            _valueObjectsService = productSoldService;
            _productService = productService;
        }

        public async Task<ActionResult> Index()
        {
            var productList = await _valueObjectsService.GetAllSalesByDateAsync(DateTime.Now);
            return View(productList);
        }

        public async Task<ActionResult> BestSeillingProducts()
        {
            var bestProductList = await _valueObjectsService.BestSeillingProductsAsync();
            return View(bestProductList);
        }

        public async Task<ActionResult> PurchasesMadebyValidCustomers()
        {
            var sales = await _valueObjectsService.PurchasesMadebyValidCustomers();
            return View(sales);
        }

        public async Task<IActionResult> RegisterSale(string? saleNumber)
        {
            SaleDTO? sale = null;
            if (saleNumber != null)
                sale = await _saleService.GetSaleBySaleNumber(saleNumber);

            await GetSaleCustomerProductsAndViewBags();
            return View(sale);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegisterSale(SaleDTO? saleDto)
        {
            var product = await _productService.FindProductByIdAsync(saleDto.ProductId.Value);

            if (saleDto.ProductQuantity > product.Quantity)
            {
                ModelState.AddModelError("ProductQuantity", "The product quantity cannot be greater than product stock quantity");
                await GetSaleCustomerProductsAndViewBags();
                return View(saleDto);
            }

            if (!ModelState.IsValid) return View(saleDto);
            await _saleService.RegisterSalesAsync(saleDto);
            await _productService.ChangeStockValuesAsync(saleDto.ProductId.Value, saleDto.ProductQuantity.Value);
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Details(string? saleNumber)
        {
            var sale = await _saleService.GetSaleBySaleNumber(saleNumber);
            if (saleNumber == null) return RedirectToAction(nameof(Index));
            return View(sale);
        }

        public async Task<ActionResult> Edit(int id)
        {
            await GetSaleCustomerProductsAndViewBags();
            return RedirectToAction(nameof(RegisterSale));
        }

        private async Task GetSaleCustomerProductsAndViewBags()
        {
            var saleCustomersProducts = await _valueObjectsService.GetCustomersAndProductsForSale();
            ViewBag.CustomersDTO = saleCustomersProducts.CustomersForSaleDTO;
            ViewBag.ProductsDTO = saleCustomersProducts.ProductsForSaleDTO;
        }

        [HttpGet]
        public async Task<decimal> GetTodayProfit()
        {
            return await _saleService.GetTodayProfitAsync();
        }

        [HttpPost]
        public async Task CancelSaleBySaleNumber(string? q)
        {
            await _saleService.CancelSaleBySaleNumberAsync(q);
        }

        [HttpPost]
        public async Task RevertCancelledSaleBySaleNumber(string? q)
        {
            await _saleService.RevertCancelledSaleBySaleNumberAsync(q);
        }

        [HttpDelete]
        public async Task DeleteSale(int? id)
        {
            await _saleService.DeleteSaleAsync(id.Value);
        }
    }
}

src/WebSales.WebInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebSales.WebInterface.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome/css/all.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm text-white navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebSales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebSales.WebInterface - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/axios.min.js"></script>
    <script src="~/font-awesome/js/all.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>